baseURL = 'https://digital-literacy.codeyourfuture.io/' # update with your domain
title = 'Day to Day Skills'  #update with your site name

 # mount all the shared CYF brand assets, content, etc, from /curriculum
[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme" 

# that's all you need for config, but you can also have some fancy markdown

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true
