baseURL = 'https://digital-literacy.codeyourfuture.io/' # update with your domain
title = 'Day to Day Skills'  #update with your site name


 # mount all the shared CYF brand assets, content, etc, from /curriculum
[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme" 
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo" 

# that's all you need for config, but you can also have some fancy markdown

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
    [markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
      unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

## let's combine our themes so you can have slides out of the box
## with Dzello's module for Reveal.js
## if this mod doesn't work for you, I also built a CYF implementation
# but it's probably better to use the predone thing if pos

theme = ["github.com/CodeYourFuture/curriculum/org-cyf-theme", "github.com/dzello/reveal-hugo"]

[params]
repo = "https://github.com/CodeYourFuture/Course-DLP/"
root="Course-DLP"
  [params.logo]
    src = '/site-logo-small.svg'
    top = '20px'
    left = '20px'
    width = '50px'
  [params.appearance]
    font = 'Raleway'
    font_size = 5

[params.reveal_hugo]
    margin = 0.1
    transition = 'slide'
    transitionSpeed = 'fast'
    slideNumber = false
    controls = true
    hash = true
    respondToHashChanges = true
    jumpToSlide = true
    keyboard = true
    overview = true
    fragments = true
    fragmentInURL = true
    pause = true
    progress = true
    history = false
    center = true
    loop = false
    help = true
    mouseWheel = false
    hideAddressBar = true
    previewLinks = false
    custom_css = false
    disable_layout = false
    display = 'block'
    load_default_plugins = true
    custom_theme = "custom-theme.scss"
    custom_theme_compile = true
    [reveal_hugo.custom_theme_options]
      targetPath = "css/reveal-theme.css"
      enableSourceMap = true
    [params.reveal_hugo.templates.topic]
     background-color="hsla(330, 74%, 49%, 0.95)"
     background="linear-gradient(90deg, hsla(330, 74%, 49%, 0.95) 1%, hsla(258, 61%, 28%, 0.99))"
      transition = "zoom"
    [params.reveal.hugo.templates.objectives]
      background-color="hsl(250, 55%, 96%)"
      background-image="/bottom-chevron.svg"
      transition="fade"
    [params.reveal_hugo.templates.section]
    # purple
      background-color="hsla(258, 61%, 28%, 0.99)"
      background-image="/white-chevron.svg"
      transition = "fade"
    [params.reveal_hugo.templates.activity]
      background-color="hsl(250, 55%, 96%)"
      transition = "fade-in slide-out"
    